CREATE TABLE ROOM (
    RM_ID INT AUTO_INCREMENT PRIMARY KEY,
    RM_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    RM_TYPE ENUM('Simple', 'Double', 'Suite', 'Deluxe') NOT NULL,
    RM_DESC TEXT NOT NULL,
    RM_PRICE_PER_NIGHT DECIMAL(10, 2) NOT NULL,
    RM_STATUS ENUM('Disponible', 'Occupée', 'Réservée') DEFAULT 'Disponible',
    RM_CREATED_DATE DATETIME NULL DEFAULT NULL,
    RM_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;