CREATE TABLE EQUIPMENTROOM (
    EQMRM_EQM_ID INT NOT NULL,
    EQMRM_RM_ID INT NOT NULL,
    PRIMARY KEY (EQMRM_EQM_ID, EQMRM_RM_ID),
    CONSTRAINT FK_EQMRM_RM_ID FOREIGN KEY (EQMRM_RM_ID) REFERENCES ROOM(RM_ID) ,
    CONSTRAINT FK_EQMRM_EQM_ID FOREIGN KEY (EQMRM_EQM_ID) REFERENCES EQUIPMENT(EQM_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;