CREATE TABLE SERVICE (
    SERV_ID INT AUTO_INCREMENT PRIMARY KEY,
    SERV_NAME VARCHAR(255) NOT NULL,
    SERV_DESC TEXT NOT NULL,
    SERV_PRICE DECIMAL(10, 2) NOT NULL,
    SERV_TYPE ENUM('event', 'restoration', 'tourism') NOT NULL,
    SERV_CREATED_DATE DATETIME NULL DEFAULT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;