CREATE TABLE EVENT (
    EVT_ID INT AUTO_INCREMENT PRIMARY KEY,
    EVT_NAME VARCHAR(255) NOT NULL,
    EVT_TYPE ENUM('wedding', 'conference', 'birthday', 'funeral') NOT NULL,
    EVT_DESC TEXT NOT NULL,
    EVT_IMAGE VARCHAR(255) NULL DEFAULT NULL,
    EVT_DATE_START DATE NOT NULL,
    EVT_DATE_END DATE NOT NULL,
    EVT_LOCATION VARCHAR(255) NOT NULL,
    EVT_CREATED_DATE DATETIME NULL DEFAULT NULL,
    EVT_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;