CREATE TABLE POST (
   PT_ID INT AUTO_INCREMENT PRIMARY KEY,
   PT_US_ID INT NOT NULL,
   PT_TITLE VARCHAR(255) NOT NULL,
   PT_CONTENT TEXT NOT NULL,
   PT_IMAGE VARCHAR(255) NULL DEFAULT NULL,
   PT_CREATED_DATE DATETIME NULL DEFAULT NULL,
   CONSTRAINT FK_PT_US_ID FOREIGN KEY (PT_US_ID) REFERENCES USERS(US_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;