CREATE TABLE USERS (
    US_ID INT AUTO_INCREMENT PRIMARY KEY,
    US_NAME VARCHAR(255) NOT NULL,
    US_ROLE ENUM('client', 'admin', 'employee') DEFAULT 'client',
    US_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    US_CONTACT VARCHAR(20) NULL,
    US_PASSWORD VARCHAR(255) NULL
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;