CREATE TABLE BOOKING (
    BK_ID INT AUTO_INCREMENT PRIMARY KEY,
    BK_US_ID INT NOT NULL,
    BK_SERV_ID INT DEFAULT NULL,
    BK_RM_ID INT DEFAULT NULL,
    BK_START_DATE DATE NOT NULL,
    BK_END_DATE DATE NOT NULL,
    BK_STATUS ENUM('confirmed', 'cancelled', 'pending') DEFAULT 'pending',
    BK_CREATED_DATE DATETIME NULL DEFAULT NULL,
    BK_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
    CONSTRAINT FK_BK_US_ID FOREIGN KEY (BK_US_ID) REFERENCES USERS(US_ID),
    CONSTRAINT FK_BK_SERV_ID FOREIGN KEY (BK_SERV_ID) REFERENCES SERVICE(SERV_ID),
    CONSTRAINT FK_BK_RM_ID FOREIGN KEY (BK_RM_ID) REFERENCES ROOM(RM_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;