CREATE TABLE NOTICE (
    NT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NT_US_ID INT NOT NULL,
    NT_COMMENT TEXT NOT NULL,
    NT_NOTE INT CHECK (NOTE BETWEEN 1 AND 5),
    NT_CREATED_DATE DATETIME NULL DEFAULT NULL,
    CONSTRAINT FK_NT_US_ID FOREIGN KEY (NT_US_ID) REFERENCES USERS(US_ID) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;